name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: [0.16.0, master]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.zig-version == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Workaround Zig 0.16.0 ZIP unpack failure
        # https://codeberg.org/ziglang/zig/issues/31964
        shell: bash
        run: mkdir -p "${ZIG_GLOBAL_CACHE_DIR}/tmp"

      - name: Check Formatting
        if: runner.os != 'Windows' # zig fmt failing on Windows CI, unclear why
        run: zig fmt --ast-check --check .

      - name: Build for Windows
        run: zig build example -Dtarget=x86_64-windows-gnu --summary all

      - name: Build for Linux
        run: zig build example -Dtarget=x86_64-linux-gnu --summary all

      - name: Build for macOS
        if: runner.os == 'macOS'
        # We don't support cross compiling for macOS, so don't set a target just build
        # the native target
        run: zig build example --summary all

      - name: Build for iOS
        if: runner.os == 'macOS'
        # No cross compilation for Apple platforms, and the iOS SDK is not bundled with Zig, so
        # point Zig at Xcode's iPhoneOS SDK.
        run: zig build -Dtarget=aarch64-ios --sysroot "$(xcrun --sdk iphoneos --show-sdk-path)" --summary all
